### PR TITLE
Improve performance in description parser

### PR DESCRIPTION
**Pull request by SnGmng**
This increases the performance of description parsing by 100-200ms.
For more info see: https://github.com/Tyrrrz/YoutubeExplode/issues/222

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Do you know why is `.EndsWith` so much slower?

**Comment by SnGmng** [comment]
I have no clue, i just tested it and it was faster 😆

**Comment by SnGmng** [comment]
Im researching right now if a regex would be even faster

**Comment by Tyrrrz** [comment]
I think you misprofiled, the longest executing part if `get_InnerText`
image

**Comment by Tyrrrz** [comment]
This looks like the implementation in the version YoutubeExplode is using:
https://github.com/AngleSharp/AngleSharp/blob/f1c8bc6c6589b4b8a8cdc2c653fb65be8a977295/src/AngleSharp/Dom/Html/HtmlElement.cs#L517-561

**Comment by Tyrrrz** [comment]
Switching from `.InnerText` to `.TextContent` halved the execution time to ~650ms with your benchmarks.

**Comment by SnGmng** [comment]
Now ParseDescription is down to 18ms!
Allthough `.StartsWith` saved 200ms in my benchmarks, 
`TextContent` saved even more!

Here are my results for ParseDescription:
`.StartsWith` + `.InnerText`:  440ms
`.EndsWith` + `.InnerText`: 220ms
`.StartsWith` + `.TextContent`: 18ms
`.EndsWith` + `.TextContent`: 34ms

**Comment by Tyrrrz** [comment]
Really curious why `.EndsWith` is so much slower, but I guess in the context of 18ms vs 34ms it doesn't matter very much. I blame `AngleSharp` for not providing clear distinction between `InnerText` and `TextContent`. Ideally I'd prefer a super simple HTML parser, but there are no alternatives.

**Comment by Tyrrrz** [comment]
I'd still prefer `.EndsWith` though, because we're looking for truncated links and they end with triple dots

**Comment by SnGmng** [comment]
Ok im fine with that. 10ms wont make a difference anyway

**Pull request merged**
