### PR TITLE
Fix ChannelSlug parsing failing on URL-ecsaped characters

### PR DESCRIPTION
**Pull request by tqk2811**
Test: https://www.youtube.com/c/MuseVi%E1%BB%87tNam

### CODE REVIEW

**Comment by tqk2811** [comment]
Oh youtube have more type url : https://www.youtube.com/@MuseVietnam

**Comment by Tyrrrz** [comment]
Can we instead just URL-unescape the match before attempting to validate/parse it?

**Comment by tqk2811** [comment]
How about `HttpUtility.UrlDecode`   
```
string url = System.Web.HttpUtility.UrlDecode("https://www.youtube.com/c/MuseVi%E1%BB%87tNam");
//https://www.youtube.com/c/MuseViệtNam
```

**Comment by Tyrrrz** [comment]
> How about `HttpUtility.UrlDecode`
> 
> ```cs
> string url = System.Web.HttpUtility.UrlDecode("https://www.youtube.com/c/MuseVi%E1%BB%87tNam");
> //https://www.youtube.com/c/MuseViệtNam
> ```

I'm thinking just:

```csharp
var regularMatch = HttpUtility.UrlDecode(Regex.Match(channelSlugOrUrl, @"youtube\..+?/c/(.*?)(?:\?|&|/|$)").Groups[1].Value);
```

And please add your test URL to the tests

**Pull request merged**
