### PR TITLE
Fix GetPlaylistAsync() only returning the first 200 videos for big playlists

### LINKED ISSUE #337: GetPlaylistAsync() only returning the first 200 videos for some big playlists
The method has a mechanism which advances the index, with the intention to requests all videos of a playlist. The problem is, by advancing the index only by 100 for each page, the returned videos for the first and second request will be the same, thus there are no new videos added and the method will return.

The first request (index=0) returns up to 200 videos (0-200), with index 100 returns the same 200 videos. A request with index 200 returns videos 101 to 300.

Solution: Instead of advancing the index by a fixed amount of 100, the countDelta variable can be used to increase the index. This results in all videos returned and we do not overshoot the playlist size (which would again result in only the first 200 videos in the request.)

### PR DESCRIPTION
**Pull request by polynoman**
…playlists.

Fixes #337

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Hi, thanks for the PR.

I'm trying reaaaally hard to remember why I used 100 but I can't. I think it was because mix playlists worked differently or something? Not sure.

Could you check the playlists in test data (https://github.com/Tyrrrz/YoutubeExplode/blob/482c8707407ed4e8fb7d5fc7433539c2357653dd/YoutubeExplode.Tests/TestData.cs#L121-L131) and make sure that all of the videos are returned?

**Comment by polynoman** [comment]
I just checked the playlists from your testcase and compared the results with the new version. 
The old version has no problem processing the "large" playlist of your examples, because for that playlists the index starts at 1. For the playlist "OLAK5uy_mtOdjCW76nDvf5yOzgcAVMYpJ5gcW5uKU" the index starts with zero, which will result in no new video in the second request thus, the stopping. You should add this playlist to the testcases.

For the "my mix" playlist, the return seems to be a bit random for both cases. Both will stop when there is no new video in the next request (countDelta = 0).

**Comment by Tyrrrz** [comment]
Cool. So what I'm hearing is that the test playlists (except my mix) work correctly with your change? In that case, please add `OLAK5uy_mtOdjCW76nDvf5yOzgcAVMYpJ5gcW5uKU` to the test cases and I will merge it.

**Comment by polynoman** [comment]
I just saw, that for the "large" the last few videos get lost. When the index starts with 1, adding `countDelta` will cause an overshoot in the end, resulting in some videos lost. By adding `countDelta -1` instead, we will not overshoot.

Is there a reason to start the index with 1 sometimes?

The index will be defined here:
`var index = playlistId.StartsWith("PL", StringComparison.OrdinalIgnoreCase) ? 101 : 0;`

If it is set to zero, adding just `countDelta` to the index will be fine.

**Comment by Tyrrrz** [comment]
That changed seems to have been made to fix this issue: https://github.com/Tyrrrz/YoutubeExplode/issues/259

**Comment by polynoman** [comment]
Ok, from what is see, the index is 101 when the playlist-code starts with PL, else it is 0.

For the channel case from #259 this computation will be 0 and it works fine.
If we use `countDelta` to advance the index, we can start with 0 for normal playlists as well, which then works fine for both the "large" playlist and my "large alternative"  `OLAK5uy_mtOdjCW76nDvf5yOzgcAVMYpJ5gcW5uKU` playlist.

So I recommend `var index = 0;` for all cases.

**Comment by Tyrrrz** [comment]
Very well then :)
Please add your "large alternative" playlist to tests as well.

**Comment by polynoman** [comment]
Done 👍

**Comment by Tyrrrz** [comment]
Looks good.

I noticed that https://www.youtube.com/playlist?list=RDCLAK5uy_lf8okgl2ygD075nhnJVjlfhwp8NsUgEbs shows 91 videos but YoutubeExplode returns only the *first* 26 videos it seems. This happens on old version as well so it's a separate issue.

**Pull request merged**
