### PR TITLE
Added url properties to the video model

### PR DESCRIPTION
**Pull request by TheInsaneBro**
This can be useful in places where we e.g. get some videos over a playlist and want to use the video urls somewhere. I think the actual YouTube-library is the best place for such a conversion (from id to url).

Let me know what you think about it.

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Hi, thanks for PR. 

1. Can you move opening braces to new lines to be consistent with the rest of the code?
2. `Id` is never null by design
3. I think it would make more sense to move these to `Models.Extensions` class. I usually try to only keep integral properties inside model objects and move everything that can be derived to extensions.

**Comment by Tyrrrz** [comment]
Thanks! Tell me when it's safe to merge.

**Comment by TheInsaneBro** [comment]
It's ready :+1:

**Comment by Tyrrrz** [comment]
Merged

**Pull request merged**
