### PR TITLE
Added support for a new type of playlists

### PR DESCRIPTION
**Pull request by shaked6540**
(this is my first pull request please don't roast me)

This basically adds support for what I mentioned in #152 

Btw, this fails a unit test for a playlist with an ID which is supposed to be too long, but this new type of playlist has an id with the length of 41 characters and the test that suppose to fail has 35

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Hi and thanks!
Can you fix the tests so they are not failing?

**Comment by Tyrrrz** [comment]
I still have doubts that the only defining feature of this playlist is that it doesn't have statistics. It looks like all videos inside of it are music videos but unfortunately I cannot watch them as they are unavailable for me.

**Comment by Tyrrrz** [comment]
Do you know of any other examples that use this playlist type?

**Comment by shaked6540** [comment]
No I haven't stumbled upon any of them, a user that uses my GUI wrapper for this library reported that it can't download this specific playlist. I'll try to get in touch with them

**Comment by Tyrrrz** [comment]
Yeah this indeed looks like some autogenerated music playlist. Interesting. I do remember there was a PL type with a very long ID which was sort of like a mix playlist, based on an artist, while this one looks like a mix playlist based on an album.

**Comment by Tyrrrz** [comment]
Also what is the project you're developing? I'm curious. 😁

**Comment by Tyrrrz** [comment]
Okay, I've done some extra research and I'm tempted to rename `NormalWithoutStatistics` to `MusicAlbum`.

**Comment by shaked6540** [comment]
The project I'm working on is https://github.com/shaked6540/YoutubePlaylistDownloader 
It's still not perfect but I'm trying to make it perfect slowly

And yeah I think `MusicAlbum` would fit more, I'll update it

**Comment by Tyrrrz** [comment]
🎉

**Pull request merged**
