### PR TITLE
WIP: Get playlists from channel/user page

### PR DESCRIPTION
**Pull request by Zyano**
This is still very much work in progress.
PR based on discussion from #44

A few things to note:
* This PR includes all the models used to parse the JSON from the channel/user page and the API used afterwards
* It attempts to cache the youutube api version used in the header to reduce the page load time after the first request by changing to the youtube ?pbj=1 and browse_ajax API
* It uses anglesharp and anglesharp.io which requires **.netstadnard2.0**
* A better public interfaces is still required

### CODE REVIEW

**Comment by Tyrrrz** [comment]
198 files changed 😨

**Comment by Zyano** [comment]
Yeah it's mostly the models required for parsing the entire youtube json model.

Ignore anything inside the folders Converter and YoutubeChannelPageModels.

**Comment by Zyano** [comment]
I've gone a head and forced pushed the same changed but in a logic order now :)  This should make it easier to review and understand what has actually been done.

**Comment by Tyrrrz** [comment]
I think it's way too much overhead for one feature, unfortunately.

**Comment by Zyano** [comment]
Okay, in that case lets close the PR then

**Comment by Tyrrrz** [comment]
Sorry about that. Thanks for the effort though.

**Pull request closed without merging**
