### PR TITLE
Use latest AngleSharp for NetStandard1.3+

### PR DESCRIPTION
**Pull request by Tirraon**
See #206
I don't really like this solution with #if directive, but it seems impossible to do in other way.
And I don't know any other lightweight alternatives.

With this PR users on net45 and netstandard1.1 will reference latest possible for them version - 0.9.11.

Before this PR I couldn't use latest AngleSharp with latest YoutubeExplode.

### CODE REVIEW

**Comment by Tyrrrz** [comment]
I'm seriously just considering writing my own lightweight read-only HTML parser to get rid of AngleSharp. Or maybe there's an alternative we can use instead?

**Comment by Tyrrrz** [comment]
Clarification: I think your solution is really good considering the circumstences, I just hate that we have to do this :(

**Comment by Tyrrrz** [comment]
Hi, just wanted to let you know I'm working on [my own parser](https://github.com/Tyrrrz/LtGt) to kill off dependency on AngleSharp. It needs a little effort and it should be ready soon.

**Comment by Tirraon** [comment]
@Tyrrrz nice!
I will close this PR.

**Comment by Tyrrrz** [comment]
Thanks for the PR though :)
Hopefully I will be able to add CSS selectors to LtGt soon and it should be enough.

**Pull request closed without merging**
